[package]
name = "swagger-rust-rocket"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde_json = "1.0.36"
